name: pyforecast

dependencies:
  - python=3.8
  - pip>=20.1.1
  - numpy
  - scipy
  - pandas
  - pyqtgraph
  - pyqtchart
  - requests
  - scikit-learn
  - matplotlib
  - pyqt=5.9.2
  - openpyxl
  - configparser
  - xlrd
  - bitarray
  - statsmodels
  - pip:
    - zeep
    - datetime
    - staty
    - geojson
    - fuzzywuzzy