name: pyforecast

dependencies:
  - python=3.6
  - pip>=20.1.1
  - pip:
    - zeep==3.4.0
    - geojson==2.5.0
    - fuzzywuzzy==0.18.0
    - bitarray==1.5.3
    - isodate==0.6.0
    - matplotlib==3.3.2
    - openpyxl==3.0.5
    - requests==2.24.0
    - numpy==1.19.2
    - scipy==1.5.2
    - scikit-learn==0.23.2
    - tqdm==4.49.0
    - xlrd==1.2.0
    - statsmodels==0.12.0
    - pandas==1.1.2
    - PyQt5==5.13.0
    - PyQtChart==5.13.0
    - pyqtgraph==0.11.0
    - PyQtWebEngine==5.13.0
    - pyqt5-tools==5.13.0.1.5