divisions = {
    "Arizona, NORTHWEST": {
        "FID": -1,
        "OBJECTID": 113,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 1,
        "STATE_CODE": 2,
        "CLIMDIV": 201,
        "CD_NEW": 1,
        "FIPS_CD": 401,
        "NCDC_GEO_I": 23,
        "NAME": "NORTHWEST",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 114,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 2,
        "STATE_CODE": 2,
        "CLIMDIV": 202,
        "CD_NEW": 2,
        "FIPS_CD": 402,
        "NCDC_GEO_I": 24,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 115,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 5,
        "STATE_CODE": 2,
        "CLIMDIV": 205,
        "CD_NEW": 5,
        "FIPS_CD": 405,
        "NCDC_GEO_I": 25,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 116,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 3,
        "STATE_CODE": 2,
        "CLIMDIV": 203,
        "CD_NEW": 3,
        "FIPS_CD": 403,
        "NCDC_GEO_I": 26,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 117,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 6,
        "STATE_CODE": 2,
        "CLIMDIV": 206,
        "CD_NEW": 6,
        "FIPS_CD": 406,
        "NCDC_GEO_I": 27,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 118,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 4,
        "STATE_CODE": 2,
        "CLIMDIV": 204,
        "CD_NEW": 4,
        "FIPS_CD": 404,
        "NCDC_GEO_I": 28,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Arizona, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 119,
        "STATE": "Arizona",
        "STATE_FIPS": 4,
        "CD_2DIG": 7,
        "STATE_CODE": 2,
        "CLIMDIV": 207,
        "CD_NEW": 7,
        "FIPS_CD": 407,
        "NCDC_GEO_I": 29,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "AZ",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, SOUTHEAST DESERT BASIN": {
        "FID": -1,
        "OBJECTID": 48,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 7,
        "STATE_CODE": 4,
        "CLIMDIV": 407,
        "CD_NEW": 7,
        "FIPS_CD": 607,
        "NCDC_GEO_I": 302,
        "NAME": "SOUTHEAST DESERT BASIN",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, NORTHEAST INTER. BASINS": {
        "FID": -1,
        "OBJECTID": 49,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 3,
        "STATE_CODE": 4,
        "CLIMDIV": 403,
        "CD_NEW": 3,
        "FIPS_CD": 603,
        "NCDC_GEO_I": 303,
        "NAME": "NORTHEAST INTER. BASINS",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, SACRAMENTO DRNG.": {
        "FID": -1,
        "OBJECTID": 50,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 2,
        "STATE_CODE": 4,
        "CLIMDIV": 402,
        "CD_NEW": 2,
        "FIPS_CD": 602,
        "NCDC_GEO_I": 304,
        "NAME": "SACRAMENTO DRNG.",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, SAN JOAQUIN DRNG.": {
        "FID": -1,
        "OBJECTID": 51,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 5,
        "STATE_CODE": 4,
        "CLIMDIV": 405,
        "CD_NEW": 5,
        "FIPS_CD": 605,
        "NCDC_GEO_I": 305,
        "NAME": "SAN JOAQUIN DRNG.",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, NORTH COAST DRAINAGE": {
        "FID": -1,
        "OBJECTID": 52,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 1,
        "STATE_CODE": 4,
        "CLIMDIV": 401,
        "CD_NEW": 1,
        "FIPS_CD": 601,
        "NCDC_GEO_I": 306,
        "NAME": "NORTH COAST DRAINAGE",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, CENTRAL COAST DRNG.": {
        "FID": -1,
        "OBJECTID": 53,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 4,
        "STATE_CODE": 4,
        "CLIMDIV": 404,
        "CD_NEW": 4,
        "FIPS_CD": 604,
        "NCDC_GEO_I": 307,
        "NAME": "CENTRAL COAST DRNG.",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "California, SOUTH COAST DRNG.": {
        "FID": -1,
        "OBJECTID": 54,
        "STATE": "California",
        "STATE_FIPS": 6,
        "CD_2DIG": 6,
        "STATE_CODE": 4,
        "CLIMDIV": 406,
        "CD_NEW": 6,
        "FIPS_CD": 606,
        "NCDC_GEO_I": 308,
        "NAME": "SOUTH COAST DRNG.",
        "ST_ABBRV": "CA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Colorado, PLATTE DRAINAGE BASIN": {
        "FID": -1,
        "OBJECTID": 43,
        "STATE": "Colorado",
        "STATE_FIPS": 8,
        "CD_2DIG": 4,
        "STATE_CODE": 5,
        "CLIMDIV": 504,
        "CD_NEW": 4,
        "FIPS_CD": 804,
        "NCDC_GEO_I": 297,
        "NAME": "PLATTE DRAINAGE BASIN",
        "ST_ABBRV": "CO",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Colorado, COLORADO DRAINAGE BASIN": {
        "FID": -1,
        "OBJECTID": 44,
        "STATE": "Colorado",
        "STATE_FIPS": 8,
        "CD_2DIG": 2,
        "STATE_CODE": 5,
        "CLIMDIV": 502,
        "CD_NEW": 2,
        "FIPS_CD": 802,
        "NCDC_GEO_I": 298,
        "NAME": "COLORADO DRAINAGE BASIN",
        "ST_ABBRV": "CO",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Colorado, RIO GRANDE DRAINAGE BASIN": {
        "FID": -1,
        "OBJECTID": 45,
        "STATE": "Colorado",
        "STATE_FIPS": 8,
        "CD_2DIG": 5,
        "STATE_CODE": 5,
        "CLIMDIV": 505,
        "CD_NEW": 5,
        "FIPS_CD": 805,
        "NCDC_GEO_I": 299,
        "NAME": "RIO GRANDE DRAINAGE BASIN",
        "ST_ABBRV": "CO",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Colorado, ARKANSAS DRAINAGE BASIN": {
        "FID": -1,
        "OBJECTID": 46,
        "STATE": "Colorado",
        "STATE_FIPS": 8,
        "CD_2DIG": 1,
        "STATE_CODE": 5,
        "CLIMDIV": 501,
        "CD_NEW": 1,
        "FIPS_CD": 801,
        "NCDC_GEO_I": 300,
        "NAME": "ARKANSAS DRAINAGE BASIN",
        "ST_ABBRV": "CO",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Colorado, KANSAS DRAINAGE BASIN": {
        "FID": -1,
        "OBJECTID": 47,
        "STATE": "Colorado",
        "STATE_FIPS": 8,
        "CD_2DIG": 3,
        "STATE_CODE": 5,
        "CLIMDIV": 503,
        "CD_NEW": 3,
        "FIPS_CD": 803,
        "NCDC_GEO_I": 301,
        "NAME": "KANSAS DRAINAGE BASIN",
        "ST_ABBRV": "CO",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, PANHANDLE": {
        "FID": -1,
        "OBJECTID": 93,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 1,
        "STATE_CODE": 10,
        "CLIMDIV": 1001,
        "CD_NEW": 1,
        "FIPS_CD": 1601,
        "NCDC_GEO_I": 3,
        "NAME": "PANHANDLE",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, NORTH CENTRAL PRAIRIES": {
        "FID": -1,
        "OBJECTID": 94,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 2,
        "STATE_CODE": 10,
        "CLIMDIV": 1002,
        "CD_NEW": 2,
        "FIPS_CD": 1602,
        "NCDC_GEO_I": 4,
        "NAME": "NORTH CENTRAL PRAIRIES",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, CENTRAL MOUNTAINS": {
        "FID": -1,
        "OBJECTID": 96,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 4,
        "STATE_CODE": 10,
        "CLIMDIV": 1004,
        "CD_NEW": 4,
        "FIPS_CD": 1604,
        "NCDC_GEO_I": 6,
        "NAME": "CENTRAL MOUNTAINS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, SOUTHWESTERN VALLEYS": {
        "FID": -1,
        "OBJECTID": 97,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 5,
        "STATE_CODE": 10,
        "CLIMDIV": 1005,
        "CD_NEW": 5,
        "FIPS_CD": 1605,
        "NCDC_GEO_I": 7,
        "NAME": "SOUTHWESTERN VALLEYS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, CENTRAL PLAINS": {
        "FID": -1,
        "OBJECTID": 98,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 7,
        "STATE_CODE": 10,
        "CLIMDIV": 1007,
        "CD_NEW": 7,
        "FIPS_CD": 1607,
        "NCDC_GEO_I": 8,
        "NAME": "CENTRAL PLAINS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, SOUTHWESTERN HIGHLANDS": {
        "FID": -1,
        "OBJECTID": 99,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 6,
        "STATE_CODE": 10,
        "CLIMDIV": 1006,
        "CD_NEW": 6,
        "FIPS_CD": 1606,
        "NCDC_GEO_I": 9,
        "NAME": "SOUTHWESTERN HIGHLANDS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, EASTERN HIGHLANDS": {
        "FID": -1,
        "OBJECTID": 101,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 10,
        "STATE_CODE": 10,
        "CLIMDIV": 1010,
        "CD_NEW": 10,
        "FIPS_CD": 1610,
        "NCDC_GEO_I": 11,
        "NAME": "EASTERN HIGHLANDS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, NORTHEASTERN VALLEYS": {
        "FID": -1,
        "OBJECTID": 102,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 8,
        "STATE_CODE": 10,
        "CLIMDIV": 1008,
        "CD_NEW": 8,
        "FIPS_CD": 1608,
        "NCDC_GEO_I": 12,
        "NAME": "NORTHEASTERN VALLEYS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, NORTH CENTRAL CANYONS": {
        "FID": -1,
        "OBJECTID": 95,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 3,
        "STATE_CODE": 10,
        "CLIMDIV": 1003,
        "CD_NEW": 3,
        "FIPS_CD": 1603,
        "NCDC_GEO_I": 5,
        "NAME": "NORTH CENTRAL CANYONS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Idaho, UPPER SNAKE RIVER PLAINS": {
        "FID": -1,
        "OBJECTID": 100,
        "STATE": "Idaho",
        "STATE_FIPS": 16,
        "CD_2DIG": 9,
        "STATE_CODE": 10,
        "CLIMDIV": 1009,
        "CD_NEW": 9,
        "FIPS_CD": 1609,
        "NCDC_GEO_I": 10,
        "NAME": "UPPER SNAKE RIVER PLAINS",
        "ST_ABBRV": "ID",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, NORTHWEST": {
        "FID": -1,
        "OBJECTID": 182,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 1,
        "STATE_CODE": 14,
        "CLIMDIV": 1401,
        "CD_NEW": 1,
        "FIPS_CD": 2001,
        "NCDC_GEO_I": 92,
        "NAME": "NORTHWEST",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 184,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 3,
        "STATE_CODE": 14,
        "CLIMDIV": 1403,
        "CD_NEW": 3,
        "FIPS_CD": 2003,
        "NCDC_GEO_I": 94,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, WEST CENTRAL": {
        "FID": -1,
        "OBJECTID": 185,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 4,
        "STATE_CODE": 14,
        "CLIMDIV": 1404,
        "CD_NEW": 4,
        "FIPS_CD": 2004,
        "NCDC_GEO_I": 95,
        "NAME": "WEST CENTRAL",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, CENTRAL": {
        "FID": -1,
        "OBJECTID": 186,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 5,
        "STATE_CODE": 14,
        "CLIMDIV": 1405,
        "CD_NEW": 5,
        "FIPS_CD": 2005,
        "NCDC_GEO_I": 96,
        "NAME": "CENTRAL",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 187,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 6,
        "STATE_CODE": 14,
        "CLIMDIV": 1406,
        "CD_NEW": 6,
        "FIPS_CD": 2006,
        "NCDC_GEO_I": 97,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 188,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 7,
        "STATE_CODE": 14,
        "CLIMDIV": 1407,
        "CD_NEW": 7,
        "FIPS_CD": 2007,
        "NCDC_GEO_I": 98,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 189,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 8,
        "STATE_CODE": 14,
        "CLIMDIV": 1408,
        "CD_NEW": 8,
        "FIPS_CD": 2008,
        "NCDC_GEO_I": 99,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Kansas, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 190,
        "STATE": "Kansas",
        "STATE_FIPS": 20,
        "CD_2DIG": 9,
        "STATE_CODE": 14,
        "CLIMDIV": 1409,
        "CD_NEW": 9,
        "FIPS_CD": 2009,
        "NCDC_GEO_I": 100,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "KS",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, WESTERN": {
        "FID": -1,
        "OBJECTID": 253,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 1,
        "STATE_CODE": 24,
        "CLIMDIV": 2401,
        "CD_NEW": 1,
        "FIPS_CD": 3001,
        "NCDC_GEO_I": 163,
        "NAME": "WESTERN",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 254,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 3,
        "STATE_CODE": 24,
        "CLIMDIV": 2403,
        "CD_NEW": 3,
        "FIPS_CD": 3003,
        "NCDC_GEO_I": 164,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, NORTHEASTERN": {
        "FID": -1,
        "OBJECTID": 255,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 6,
        "STATE_CODE": 24,
        "CLIMDIV": 2406,
        "CD_NEW": 6,
        "FIPS_CD": 3006,
        "NCDC_GEO_I": 165,
        "NAME": "NORTHEASTERN",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, CENTRAL": {
        "FID": -1,
        "OBJECTID": 256,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 4,
        "STATE_CODE": 24,
        "CLIMDIV": 2404,
        "CD_NEW": 4,
        "FIPS_CD": 3004,
        "NCDC_GEO_I": 166,
        "NAME": "CENTRAL",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, SOUTHWESTERN": {
        "FID": -1,
        "OBJECTID": 257,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 2,
        "STATE_CODE": 24,
        "CLIMDIV": 2402,
        "CD_NEW": 2,
        "FIPS_CD": 3002,
        "NCDC_GEO_I": 167,
        "NAME": "SOUTHWESTERN",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 258,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 5,
        "STATE_CODE": 24,
        "CLIMDIV": 2405,
        "CD_NEW": 5,
        "FIPS_CD": 3005,
        "NCDC_GEO_I": 168,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Montana, SOUTHEASTERN": {
        "FID": -1,
        "OBJECTID": 259,
        "STATE": "Montana",
        "STATE_FIPS": 30,
        "CD_2DIG": 7,
        "STATE_CODE": 24,
        "CLIMDIV": 2407,
        "CD_NEW": 7,
        "FIPS_CD": 3007,
        "NCDC_GEO_I": 169,
        "NAME": "SOUTHEASTERN",
        "ST_ABBRV": "MT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, PANHANDLE": {
        "FID": -1,
        "OBJECTID": 269,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 1,
        "STATE_CODE": 25,
        "CLIMDIV": 2501,
        "CD_NEW": 1,
        "FIPS_CD": 3101,
        "NCDC_GEO_I": 179,
        "NAME": "PANHANDLE",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 270,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 2,
        "STATE_CODE": 25,
        "CLIMDIV": 2502,
        "CD_NEW": 2,
        "FIPS_CD": 3102,
        "NCDC_GEO_I": 180,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 271,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 3,
        "STATE_CODE": 25,
        "CLIMDIV": 2503,
        "CD_NEW": 3,
        "FIPS_CD": 3103,
        "NCDC_GEO_I": 181,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 272,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 7,
        "STATE_CODE": 25,
        "CLIMDIV": 2507,
        "CD_NEW": 7,
        "FIPS_CD": 3107,
        "NCDC_GEO_I": 182,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, CENTRAL": {
        "FID": -1,
        "OBJECTID": 273,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 5,
        "STATE_CODE": 25,
        "CLIMDIV": 2505,
        "CD_NEW": 5,
        "FIPS_CD": 3105,
        "NCDC_GEO_I": 183,
        "NAME": "CENTRAL",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 274,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 6,
        "STATE_CODE": 25,
        "CLIMDIV": 2506,
        "CD_NEW": 6,
        "FIPS_CD": 3106,
        "NCDC_GEO_I": 184,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 275,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 8,
        "STATE_CODE": 25,
        "CLIMDIV": 2508,
        "CD_NEW": 8,
        "FIPS_CD": 3108,
        "NCDC_GEO_I": 185,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nebraska, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 276,
        "STATE": "Nebraska",
        "STATE_FIPS": 31,
        "CD_2DIG": 9,
        "STATE_CODE": 25,
        "CLIMDIV": 2509,
        "CD_NEW": 9,
        "FIPS_CD": 3109,
        "NCDC_GEO_I": 186,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "NE",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nevada, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 55,
        "STATE": "Nevada",
        "STATE_FIPS": 32,
        "CD_2DIG": 3,
        "STATE_CODE": 26,
        "CLIMDIV": 2603,
        "CD_NEW": 3,
        "FIPS_CD": 3203,
        "NCDC_GEO_I": 309,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "NV",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nevada, NORTHEASTERN": {
        "FID": -1,
        "OBJECTID": 56,
        "STATE": "Nevada",
        "STATE_FIPS": 32,
        "CD_2DIG": 2,
        "STATE_CODE": 26,
        "CLIMDIV": 2602,
        "CD_NEW": 2,
        "FIPS_CD": 3202,
        "NCDC_GEO_I": 310,
        "NAME": "NORTHEASTERN",
        "ST_ABBRV": "NV",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nevada, NORTHWESTERN": {
        "FID": -1,
        "OBJECTID": 57,
        "STATE": "Nevada",
        "STATE_FIPS": 32,
        "CD_2DIG": 1,
        "STATE_CODE": 26,
        "CLIMDIV": 2601,
        "CD_NEW": 1,
        "FIPS_CD": 3201,
        "NCDC_GEO_I": 311,
        "NAME": "NORTHWESTERN",
        "ST_ABBRV": "NV",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Nevada, EXTREME SOUTHERN": {
        "FID": -1,
        "OBJECTID": 58,
        "STATE": "Nevada",
        "STATE_FIPS": 32,
        "CD_2DIG": 4,
        "STATE_CODE": 26,
        "CLIMDIV": 2604,
        "CD_NEW": 4,
        "FIPS_CD": 3204,
        "NCDC_GEO_I": 312,
        "NAME": "EXTREME SOUTHERN",
        "ST_ABBRV": "NV",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, CENTRAL VALLEY": {
        "FID": -1,
        "OBJECTID": 91,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 5,
        "STATE_CODE": 29,
        "CLIMDIV": 2905,
        "CD_NEW": 5,
        "FIPS_CD": 3505,
        "NCDC_GEO_I": 1,
        "NAME": "CENTRAL VALLEY",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, CENTRAL HIGHLANDS": {
        "FID": -1,
        "OBJECTID": 92,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 6,
        "STATE_CODE": 29,
        "CLIMDIV": 2906,
        "CD_NEW": 6,
        "FIPS_CD": 3506,
        "NCDC_GEO_I": 2,
        "NAME": "CENTRAL HIGHLANDS",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, NORTHEASTERN PLAINS": {
        "FID": -1,
        "OBJECTID": 85,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 3,
        "STATE_CODE": 29,
        "CLIMDIV": 2903,
        "CD_NEW": 3,
        "FIPS_CD": 3503,
        "NCDC_GEO_I": 339,
        "NAME": "NORTHEASTERN PLAINS",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, SOUTHEASTERN PLAINS": {
        "FID": -1,
        "OBJECTID": 86,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 7,
        "STATE_CODE": 29,
        "CLIMDIV": 2907,
        "CD_NEW": 7,
        "FIPS_CD": 3507,
        "NCDC_GEO_I": 340,
        "NAME": "SOUTHEASTERN PLAINS",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, NORTHWESTERN PLATEAU": {
        "FID": -1,
        "OBJECTID": 87,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 1,
        "STATE_CODE": 29,
        "CLIMDIV": 2901,
        "CD_NEW": 1,
        "FIPS_CD": 3501,
        "NCDC_GEO_I": 341,
        "NAME": "NORTHWESTERN PLATEAU",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, NORTHERN MOUNTAINS": {
        "FID": -1,
        "OBJECTID": 88,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 2,
        "STATE_CODE": 29,
        "CLIMDIV": 2902,
        "CD_NEW": 2,
        "FIPS_CD": 3502,
        "NCDC_GEO_I": 342,
        "NAME": "NORTHERN MOUNTAINS",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, SOUTHERN DESERT": {
        "FID": -1,
        "OBJECTID": 89,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 8,
        "STATE_CODE": 29,
        "CLIMDIV": 2908,
        "CD_NEW": 8,
        "FIPS_CD": 3508,
        "NCDC_GEO_I": 343,
        "NAME": "SOUTHERN DESERT",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "New Mexico, SOUTHWESTERN MOUNTAINS": {
        "FID": -1,
        "OBJECTID": 90,
        "STATE": "New Mexico",
        "STATE_FIPS": 35,
        "CD_2DIG": 4,
        "STATE_CODE": 29,
        "CLIMDIV": 2904,
        "CD_NEW": 4,
        "FIPS_CD": 3504,
        "NCDC_GEO_I": 344,
        "NAME": "SOUTHWESTERN MOUNTAINS",
        "ST_ABBRV": "NM",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, NORTHWEST": {
        "FID": -1,
        "OBJECTID": 260,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 1,
        "STATE_CODE": 32,
        "CLIMDIV": 3201,
        "CD_NEW": 1,
        "FIPS_CD": 3801,
        "NCDC_GEO_I": 170,
        "NAME": "NORTHWEST",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 261,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 2,
        "STATE_CODE": 32,
        "CLIMDIV": 3202,
        "CD_NEW": 2,
        "FIPS_CD": 3802,
        "NCDC_GEO_I": 171,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, WEST CENTRAL": {
        "FID": -1,
        "OBJECTID": 263,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 4,
        "STATE_CODE": 32,
        "CLIMDIV": 3204,
        "CD_NEW": 4,
        "FIPS_CD": 3804,
        "NCDC_GEO_I": 173,
        "NAME": "WEST CENTRAL",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, CENTRAL": {
        "FID": -1,
        "OBJECTID": 264,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 5,
        "STATE_CODE": 32,
        "CLIMDIV": 3205,
        "CD_NEW": 5,
        "FIPS_CD": 3805,
        "NCDC_GEO_I": 174,
        "NAME": "CENTRAL",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 265,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 6,
        "STATE_CODE": 32,
        "CLIMDIV": 3206,
        "CD_NEW": 6,
        "FIPS_CD": 3806,
        "NCDC_GEO_I": 175,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 267,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 8,
        "STATE_CODE": 32,
        "CLIMDIV": 3208,
        "CD_NEW": 8,
        "FIPS_CD": 3808,
        "NCDC_GEO_I": 177,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 268,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 9,
        "STATE_CODE": 32,
        "CLIMDIV": 3209,
        "CD_NEW": 9,
        "FIPS_CD": 3809,
        "NCDC_GEO_I": 178,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 266,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 7,
        "STATE_CODE": 32,
        "CLIMDIV": 3207,
        "CD_NEW": 7,
        "FIPS_CD": 3807,
        "NCDC_GEO_I": 176,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "North Dakota, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 262,
        "STATE": "North Dakota",
        "STATE_FIPS": 38,
        "CD_2DIG": 3,
        "STATE_CODE": 32,
        "CLIMDIV": 3203,
        "CD_NEW": 3,
        "FIPS_CD": 3803,
        "NCDC_GEO_I": 172,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "ND",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, PANHANDLE": {
        "FID": -1,
        "OBJECTID": 277,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 1,
        "STATE_CODE": 34,
        "CLIMDIV": 3401,
        "CD_NEW": 1,
        "FIPS_CD": 4001,
        "NCDC_GEO_I": 187,
        "NAME": "PANHANDLE",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 278,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 2,
        "STATE_CODE": 34,
        "CLIMDIV": 3402,
        "CD_NEW": 2,
        "FIPS_CD": 4002,
        "NCDC_GEO_I": 188,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 279,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 3,
        "STATE_CODE": 34,
        "CLIMDIV": 3403,
        "CD_NEW": 3,
        "FIPS_CD": 4003,
        "NCDC_GEO_I": 189,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, WEST CENTRAL": {
        "FID": -1,
        "OBJECTID": 280,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 4,
        "STATE_CODE": 34,
        "CLIMDIV": 3404,
        "CD_NEW": 4,
        "FIPS_CD": 4004,
        "NCDC_GEO_I": 190,
        "NAME": "WEST CENTRAL",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, CENTRAL": {
        "FID": -1,
        "OBJECTID": 281,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 5,
        "STATE_CODE": 34,
        "CLIMDIV": 3405,
        "CD_NEW": 5,
        "FIPS_CD": 4005,
        "NCDC_GEO_I": 191,
        "NAME": "CENTRAL",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 282,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 6,
        "STATE_CODE": 34,
        "CLIMDIV": 3406,
        "CD_NEW": 6,
        "FIPS_CD": 4006,
        "NCDC_GEO_I": 192,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 283,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 7,
        "STATE_CODE": 34,
        "CLIMDIV": 3407,
        "CD_NEW": 7,
        "FIPS_CD": 4007,
        "NCDC_GEO_I": 193,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 284,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 8,
        "STATE_CODE": 34,
        "CLIMDIV": 3408,
        "CD_NEW": 8,
        "FIPS_CD": 4008,
        "NCDC_GEO_I": 194,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oklahoma, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 285,
        "STATE": "Oklahoma",
        "STATE_FIPS": 40,
        "CD_2DIG": 9,
        "STATE_CODE": 34,
        "CLIMDIV": 3409,
        "CD_NEW": 9,
        "FIPS_CD": 4009,
        "NCDC_GEO_I": 195,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "OK",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 76,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 9,
        "STATE_CODE": 35,
        "CLIMDIV": 3509,
        "CD_NEW": 9,
        "FIPS_CD": 4109,
        "NCDC_GEO_I": 330,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 77,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 7,
        "STATE_CODE": 35,
        "CLIMDIV": 3507,
        "CD_NEW": 7,
        "FIPS_CD": 4107,
        "NCDC_GEO_I": 331,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, HIGH PLATEAU": {
        "FID": -1,
        "OBJECTID": 78,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 5,
        "STATE_CODE": 35,
        "CLIMDIV": 3505,
        "CD_NEW": 5,
        "FIPS_CD": 4105,
        "NCDC_GEO_I": 332,
        "NAME": "HIGH PLATEAU",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, SOUTHWESTERN VALLEYS": {
        "FID": -1,
        "OBJECTID": 79,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 3,
        "STATE_CODE": 35,
        "CLIMDIV": 3503,
        "CD_NEW": 3,
        "FIPS_CD": 4103,
        "NCDC_GEO_I": 333,
        "NAME": "SOUTHWESTERN VALLEYS",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, NORTHERN CASCADES": {
        "FID": -1,
        "OBJECTID": 80,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 4,
        "STATE_CODE": 35,
        "CLIMDIV": 3504,
        "CD_NEW": 4,
        "FIPS_CD": 4104,
        "NCDC_GEO_I": 334,
        "NAME": "NORTHERN CASCADES",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 81,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 6,
        "STATE_CODE": 35,
        "CLIMDIV": 3506,
        "CD_NEW": 6,
        "FIPS_CD": 4106,
        "NCDC_GEO_I": 335,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 82,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 8,
        "STATE_CODE": 35,
        "CLIMDIV": 3508,
        "CD_NEW": 8,
        "FIPS_CD": 4108,
        "NCDC_GEO_I": 336,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, COASTAL AREA": {
        "FID": -1,
        "OBJECTID": 83,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 1,
        "STATE_CODE": 35,
        "CLIMDIV": 3501,
        "CD_NEW": 1,
        "FIPS_CD": 4101,
        "NCDC_GEO_I": 337,
        "NAME": "COASTAL AREA",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Oregon, WILLAMETTE VALLEY": {
        "FID": -1,
        "OBJECTID": 84,
        "STATE": "Oregon",
        "STATE_FIPS": 41,
        "CD_2DIG": 2,
        "STATE_CODE": 35,
        "CLIMDIV": 3502,
        "CD_NEW": 2,
        "FIPS_CD": 4102,
        "NCDC_GEO_I": 338,
        "NAME": "WILLAMETTE VALLEY",
        "ST_ABBRV": "OR",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, NORTHWEST": {
        "FID": -1,
        "OBJECTID": 344,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 1,
        "STATE_CODE": 39,
        "CLIMDIV": 3901,
        "CD_NEW": 1,
        "FIPS_CD": 4601,
        "NCDC_GEO_I": 254,
        "NAME": "NORTHWEST",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 1,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 2,
        "STATE_CODE": 39,
        "CLIMDIV": 3902,
        "CD_NEW": 2,
        "FIPS_CD": 4602,
        "NCDC_GEO_I": 255,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, NORTHEAST": {
        "FID": -1,
        "OBJECTID": 2,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 3,
        "STATE_CODE": 39,
        "CLIMDIV": 3903,
        "CD_NEW": 3,
        "FIPS_CD": 4603,
        "NCDC_GEO_I": 256,
        "NAME": "NORTHEAST",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, BLACK HILLS": {
        "FID": -1,
        "OBJECTID": 3,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 4,
        "STATE_CODE": 39,
        "CLIMDIV": 3904,
        "CD_NEW": 4,
        "FIPS_CD": 4604,
        "NCDC_GEO_I": 257,
        "NAME": "BLACK HILLS",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, CENTRAL": {
        "FID": -1,
        "OBJECTID": 4,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 6,
        "STATE_CODE": 39,
        "CLIMDIV": 3906,
        "CD_NEW": 6,
        "FIPS_CD": 4606,
        "NCDC_GEO_I": 258,
        "NAME": "CENTRAL",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, EAST CENTRAL": {
        "FID": -1,
        "OBJECTID": 5,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 7,
        "STATE_CODE": 39,
        "CLIMDIV": 3907,
        "CD_NEW": 7,
        "FIPS_CD": 4607,
        "NCDC_GEO_I": 259,
        "NAME": "EAST CENTRAL",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 6,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 9,
        "STATE_CODE": 39,
        "CLIMDIV": 3909,
        "CD_NEW": 9,
        "FIPS_CD": 4609,
        "NCDC_GEO_I": 260,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 7,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 8,
        "STATE_CODE": 39,
        "CLIMDIV": 3908,
        "CD_NEW": 8,
        "FIPS_CD": 4608,
        "NCDC_GEO_I": 261,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "South Dakota, SOUTHWEST": {
        "FID": -1,
        "OBJECTID": 8,
        "STATE": "South Dakota",
        "STATE_FIPS": 46,
        "CD_2DIG": 5,
        "STATE_CODE": 39,
        "CLIMDIV": 3905,
        "CD_NEW": 5,
        "FIPS_CD": 4605,
        "NCDC_GEO_I": 262,
        "NAME": "SOUTHWEST",
        "ST_ABBRV": "SD",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, HIGH PLAINS": {
        "FID": -1,
        "OBJECTID": 334,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 1,
        "STATE_CODE": 41,
        "CLIMDIV": 4101,
        "CD_NEW": 1,
        "FIPS_CD": 4801,
        "NCDC_GEO_I": 244,
        "NAME": "HIGH PLAINS",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, LOW ROLLING PLAINS": {
        "FID": -1,
        "OBJECTID": 335,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 2,
        "STATE_CODE": 41,
        "CLIMDIV": 4102,
        "CD_NEW": 2,
        "FIPS_CD": 4802,
        "NCDC_GEO_I": 245,
        "NAME": "LOW ROLLING PLAINS",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 336,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 3,
        "STATE_CODE": 41,
        "CLIMDIV": 4103,
        "CD_NEW": 3,
        "FIPS_CD": 4803,
        "NCDC_GEO_I": 246,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, EAST TEXAS": {
        "FID": -1,
        "OBJECTID": 337,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 4,
        "STATE_CODE": 41,
        "CLIMDIV": 4104,
        "CD_NEW": 4,
        "FIPS_CD": 4804,
        "NCDC_GEO_I": 247,
        "NAME": "EAST TEXAS",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, TRANS PECOS": {
        "FID": -1,
        "OBJECTID": 338,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 5,
        "STATE_CODE": 41,
        "CLIMDIV": 4105,
        "CD_NEW": 5,
        "FIPS_CD": 4805,
        "NCDC_GEO_I": 248,
        "NAME": "TRANS PECOS",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, EDWARDS PLATEAU": {
        "FID": -1,
        "OBJECTID": 339,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 6,
        "STATE_CODE": 41,
        "CLIMDIV": 4106,
        "CD_NEW": 6,
        "FIPS_CD": 4806,
        "NCDC_GEO_I": 249,
        "NAME": "EDWARDS PLATEAU",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 340,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 7,
        "STATE_CODE": 41,
        "CLIMDIV": 4107,
        "CD_NEW": 7,
        "FIPS_CD": 4807,
        "NCDC_GEO_I": 250,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, SOUTHERN": {
        "FID": -1,
        "OBJECTID": 341,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 9,
        "STATE_CODE": 41,
        "CLIMDIV": 4109,
        "CD_NEW": 9,
        "FIPS_CD": 4809,
        "NCDC_GEO_I": 251,
        "NAME": "SOUTHERN",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, UPPER COAST": {
        "FID": -1,
        "OBJECTID": 342,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 8,
        "STATE_CODE": 41,
        "CLIMDIV": 4108,
        "CD_NEW": 8,
        "FIPS_CD": 4808,
        "NCDC_GEO_I": 252,
        "NAME": "UPPER COAST",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Texas, LOWER VALLEY": {
        "FID": -1,
        "OBJECTID": 343,
        "STATE": "Texas",
        "STATE_FIPS": 48,
        "CD_2DIG": 10,
        "STATE_CODE": 41,
        "CLIMDIV": 4110,
        "CD_NEW": 10,
        "FIPS_CD": 4810,
        "NCDC_GEO_I": 253,
        "NAME": "LOWER VALLEY",
        "ST_ABBRV": "TX",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, WESTERN": {
        "FID": -1,
        "OBJECTID": 69,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 1,
        "STATE_CODE": 42,
        "CLIMDIV": 4201,
        "CD_NEW": 1,
        "FIPS_CD": 4901,
        "NCDC_GEO_I": 323,
        "NAME": "WESTERN",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, NORTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 70,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 3,
        "STATE_CODE": 42,
        "CLIMDIV": 4203,
        "CD_NEW": 3,
        "FIPS_CD": 4903,
        "NCDC_GEO_I": 324,
        "NAME": "NORTH CENTRAL",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, NORTHERN MOUNTAINS": {
        "FID": -1,
        "OBJECTID": 71,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 5,
        "STATE_CODE": 42,
        "CLIMDIV": 4205,
        "CD_NEW": 5,
        "FIPS_CD": 4905,
        "NCDC_GEO_I": 325,
        "NAME": "NORTHERN MOUNTAINS",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, UINTA BASIN": {
        "FID": -1,
        "OBJECTID": 72,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 6,
        "STATE_CODE": 42,
        "CLIMDIV": 4206,
        "CD_NEW": 6,
        "FIPS_CD": 4906,
        "NCDC_GEO_I": 326,
        "NAME": "UINTA BASIN",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, SOUTHEAST": {
        "FID": -1,
        "OBJECTID": 73,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 7,
        "STATE_CODE": 42,
        "CLIMDIV": 4207,
        "CD_NEW": 7,
        "FIPS_CD": 4907,
        "NCDC_GEO_I": 327,
        "NAME": "SOUTHEAST",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, SOUTH CENTRAL": {
        "FID": -1,
        "OBJECTID": 74,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 4,
        "STATE_CODE": 42,
        "CLIMDIV": 4204,
        "CD_NEW": 4,
        "FIPS_CD": 4904,
        "NCDC_GEO_I": 328,
        "NAME": "SOUTH CENTRAL",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Utah, DIXIE": {
        "FID": -1,
        "OBJECTID": 75,
        "STATE": "Utah",
        "STATE_FIPS": 49,
        "CD_2DIG": 2,
        "STATE_CODE": 42,
        "CLIMDIV": 4202,
        "CD_NEW": 2,
        "FIPS_CD": 4902,
        "NCDC_GEO_I": 329,
        "NAME": "DIXIE",
        "ST_ABBRV": "UT",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, WEST OLYMPIC COAST": {
        "FID": -1,
        "OBJECTID": 103,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 1,
        "STATE_CODE": 45,
        "CLIMDIV": 4501,
        "CD_NEW": 1,
        "FIPS_CD": 5301,
        "NCDC_GEO_I": 13,
        "NAME": "WEST OLYMPIC COAST",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, E OLYMPIC CASCADE FOOTHILLS": {
        "FID": -1,
        "OBJECTID": 104,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 4,
        "STATE_CODE": 45,
        "CLIMDIV": 4504,
        "CD_NEW": 4,
        "FIPS_CD": 5304,
        "NCDC_GEO_I": 14,
        "NAME": "E OLYMPIC CASCADE FOOTHILLS",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, NE OLYMPIC SAN JUAN": {
        "FID": -1,
        "OBJECTID": 105,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 2,
        "STATE_CODE": 45,
        "CLIMDIV": 4502,
        "CD_NEW": 2,
        "FIPS_CD": 5302,
        "NCDC_GEO_I": 15,
        "NAME": "NE OLYMPIC SAN JUAN",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, PUGET SOUND LOWLANDS": {
        "FID": -1,
        "OBJECTID": 106,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 3,
        "STATE_CODE": 45,
        "CLIMDIV": 4503,
        "CD_NEW": 3,
        "FIPS_CD": 5303,
        "NCDC_GEO_I": 16,
        "NAME": "PUGET SOUND LOWLANDS",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, EAST SLOPE CASCADES": {
        "FID": -1,
        "OBJECTID": 107,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 6,
        "STATE_CODE": 45,
        "CLIMDIV": 4506,
        "CD_NEW": 6,
        "FIPS_CD": 5306,
        "NCDC_GEO_I": 17,
        "NAME": "EAST SLOPE CASCADES",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, CASCADE MOUNTAINS WEST": {
        "FID": -1,
        "OBJECTID": 108,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 5,
        "STATE_CODE": 45,
        "CLIMDIV": 4505,
        "CD_NEW": 5,
        "FIPS_CD": 5305,
        "NCDC_GEO_I": 18,
        "NAME": "CASCADE MOUNTAINS WEST",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, CENTRAL BASIN": {
        "FID": -1,
        "OBJECTID": 109,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 8,
        "STATE_CODE": 45,
        "CLIMDIV": 4508,
        "CD_NEW": 8,
        "FIPS_CD": 5308,
        "NCDC_GEO_I": 19,
        "NAME": "CENTRAL BASIN",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, OKANOGAN BIG BEND": {
        "FID": -1,
        "OBJECTID": 110,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 7,
        "STATE_CODE": 45,
        "CLIMDIV": 4507,
        "CD_NEW": 7,
        "FIPS_CD": 5307,
        "NCDC_GEO_I": 20,
        "NAME": "OKANOGAN BIG BEND",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, NORTHEASTERN": {
        "FID": -1,
        "OBJECTID": 111,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 9,
        "STATE_CODE": 45,
        "CLIMDIV": 4509,
        "CD_NEW": 9,
        "FIPS_CD": 5309,
        "NCDC_GEO_I": 21,
        "NAME": "NORTHEASTERN",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Washington, PALOUSE BLUE MOUNTAINS": {
        "FID": -1,
        "OBJECTID": 112,
        "STATE": "Washington",
        "STATE_FIPS": 53,
        "CD_2DIG": 10,
        "STATE_CODE": 45,
        "CLIMDIV": 4510,
        "CD_NEW": 10,
        "FIPS_CD": 5310,
        "NCDC_GEO_I": 22,
        "NAME": "PALOUSE BLUE MOUNTAINS",
        "ST_ABBRV": "WA",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, YELLOWSTONE DRAINAGE": {
        "FID": -1,
        "OBJECTID": 59,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 1,
        "STATE_CODE": 48,
        "CLIMDIV": 4801,
        "CD_NEW": 1,
        "FIPS_CD": 5601,
        "NCDC_GEO_I": 313,
        "NAME": "YELLOWSTONE DRAINAGE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, SNAKE DRAINAGE": {
        "FID": -1,
        "OBJECTID": 60,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 2,
        "STATE_CODE": 48,
        "CLIMDIV": 4802,
        "CD_NEW": 2,
        "FIPS_CD": 5602,
        "NCDC_GEO_I": 314,
        "NAME": "SNAKE DRAINAGE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, BIG HORN": {
        "FID": -1,
        "OBJECTID": 61,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 4,
        "STATE_CODE": 48,
        "CLIMDIV": 4804,
        "CD_NEW": 4,
        "FIPS_CD": 5604,
        "NCDC_GEO_I": 315,
        "NAME": "BIG HORN",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, POWDER, LITTLE MISSOURI, TONGU": {
        "FID": -1,
        "OBJECTID": 62,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 5,
        "STATE_CODE": 48,
        "CLIMDIV": 4805,
        "CD_NEW": 5,
        "FIPS_CD": 5605,
        "NCDC_GEO_I": 316,
        "NAME": "POWDER, LITTLE MISSOURI, TONGU",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, BELLE FOURCHE DRAINAGE": {
        "FID": -1,
        "OBJECTID": 63,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 6,
        "STATE_CODE": 48,
        "CLIMDIV": 4806,
        "CD_NEW": 6,
        "FIPS_CD": 5606,
        "NCDC_GEO_I": 317,
        "NAME": "BELLE FOURCHE DRAINAGE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, CHEYENNE & NIOBRARA DRAINAGE": {
        "FID": -1,
        "OBJECTID": 64,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 7,
        "STATE_CODE": 48,
        "CLIMDIV": 4807,
        "CD_NEW": 7,
        "FIPS_CD": 5607,
        "NCDC_GEO_I": 318,
        "NAME": "CHEYENNE & NIOBRARA DRAINAGE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, GREEN AND BEAR DRAINAGE": {
        "FID": -1,
        "OBJECTID": 65,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 3,
        "STATE_CODE": 48,
        "CLIMDIV": 4803,
        "CD_NEW": 3,
        "FIPS_CD": 5603,
        "NCDC_GEO_I": 319,
        "NAME": "GREEN AND BEAR DRAINAGE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, UPPER PLATTE": {
        "FID": -1,
        "OBJECTID": 66,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 10,
        "STATE_CODE": 48,
        "CLIMDIV": 4810,
        "CD_NEW": 10,
        "FIPS_CD": 5610,
        "NCDC_GEO_I": 320,
        "NAME": "UPPER PLATTE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, LOWER PLATTE": {
        "FID": -1,
        "OBJECTID": 67,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 8,
        "STATE_CODE": 48,
        "CLIMDIV": 4808,
        "CD_NEW": 8,
        "FIPS_CD": 5608,
        "NCDC_GEO_I": 321,
        "NAME": "LOWER PLATTE",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    },
    "Wyoming, WIND RIVER": {
        "FID": -1,
        "OBJECTID": 68,
        "STATE": "Wyoming",
        "STATE_FIPS": 56,
        "CD_2DIG": 9,
        "STATE_CODE": 48,
        "CLIMDIV": 4809,
        "CD_NEW": 9,
        "FIPS_CD": 5609,
        "NCDC_GEO_I": 322,
        "NAME": "WIND RIVER",
        "ST_ABBRV": "WY",
        "SHAPE_AREA": 0,
        "SHAPE_LEN": 0
    }
}